clients/urls.py
from django.urls import path
from .views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, BirthdayClientsView

urlpatterns = [
    path('', ClientListView.as_view(), name='client_list'),
    path('<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('create/', ClientCreateView.as_view(), name='client_create'),
    path('<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('birthdays/', BirthdayClientsView.as_view(), name='birthday_view'),
]

    #TODO: Uncomment to include clients urls
    # path('clients/', include('clients.url')),
    # path('clients/', ClientListView.as_view(), name='client_list'),
    # path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    # path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    # path('clients/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    # path('clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),

insurance_clients_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import login_view, logout_view
from django.contrib.auth.views import LoginView
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='clients/'), name='index'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path("admin/", admin.site.urls),
    path('clients/', include('clients.urls')),
    path('insurances/', include('insurances.urls')),
]

clients/models.py
import uuid
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from insurances.models import Insurance

# KIRE: Models go here. This is data (like in a database). You define the schema of every table with this. 
# It shows which data we hold and the relationsip between the different data.

    


class Client(models.Model):

    # insurances = models.ManyToManyField(Insurance)
    GENDER_CHOICES = (
        ('male', 'Male'),
        ('female', 'Female'),
    )

    insurances = models.ManyToManyField(Insurance, verbose_name="Insurances", blank=True, null=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, blank=True, null=True)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    middle_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100)
    pronouns = models.CharField(max_length=50, blank=True, null=True)
    company = models.CharField(max_length=100, blank=True, null=True)
    birthday = models.DateField(blank=True, null=True)
    birth_location = models.CharField(max_length=100, blank=True, null=True)
    address = models.CharField(max_length=200, blank=True, null=True)
    zip_code = models.CharField(max_length=20, blank=True, null=True)
    region = models.CharField(max_length=100, blank=True, null=True)
    connection = models.CharField(max_length=100, blank=True, null=True)
    phone_home = models.CharField(max_length=20, blank=True, null=True)
    phone_mobile = models.CharField(max_length=20, blank=True, null=True)
    phone_work = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField(max_length=100, blank=True, null=True)
    website = models.URLField(max_length=200, blank=True, null=True)
    profession = models.CharField(max_length=100, blank=True, null=True)
    employer = models.CharField(max_length=100, blank=True, null=True)
    income = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    customer_since = models.DateField(blank=True, null=True)
    bank_code = models.CharField(max_length=20, blank=True, null=True)
    bank_name = models.CharField(max_length=100, blank=True, null=True)
    account_number = models.CharField(max_length=50, blank=True, null=True)
    relationship_status = models.CharField(max_length=50, blank=True, null=True)
    partner_name = models.CharField(max_length=100, blank=True, null=True)
    partner_surname = models.CharField(max_length=100, blank=True, null=True)
    kids_number = models.PositiveIntegerField(blank=True, null=True)
    children_name = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        verbose_name_plural = "Clients"

insurances/models.py
from django.db import models

# Create your models here.



class Insurance(models.Model):
    name = models.CharField(max_length=100)
    street = models.CharField(max_length=200, blank=True, null=True)
    zip_code = models.CharField(max_length=20, blank=True, null=True)
    place = models.CharField(max_length=100, blank=True, null=True)
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField(max_length=100, blank=True, null=True)
    website = models.URLField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.name

# Chatgpt mi go dade ovoa bez da mu go potrazam
# class InsurancePolicy(models.Model):
#     policy_number = models.CharField(max_length=50)
#     coverage_amount = models.DecimalField(max_digits=10, decimal_places=2)
#     start_date = models.DateField()
#     end_date = models.DateField()
#     insurance_company = models.ForeignKey(InsuranceCompany, on_delete=models.CASCADE)
#     # Add any other fields specific to your insurance policy model

#     def __str__(self):
#         return self.policy_number

# Explanation:

# InsuranceCompany: This model represents an insurance company and includes
#  fields like name, street, zip code, place, phone number, email, 
# and website.

# InsurancePolicy: This model represents an insurance policy and includes 
# fields like policy number, coverage amount, start date, end date, 
# and a foreign key to link it to an insurance company. 
# You may add any other fields that are specific to your insurance policies.

clients/forms.py
# forms.py
from django import forms
from .models import Client
from insurances.models import Insurance
from django.forms.widgets import TextInput

class DateInput(forms.DateInput):
    input_type = 'date'

    
class ClientForm(forms.ModelForm):
    insurances = forms.ModelMultipleChoiceField(
        queryset=Insurance.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'select2'}),
    )

    class Meta:
        model = Client
        fields = '__all__'
        widgets = {
            'birthday': DateInput,
        }



    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Customize the appearance of other fields if needed
        self.fields['first_name'].widget.attrs.update({'class': 'custom-class'})
        self.fields['last_name'].widget.attrs.update({'placeholder': 'Enter last name'})
        # Add more customizations as needed

clients/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.views import View
from django.utils import timezone
from datetime import timedelta

from django_tables2 import SingleTableView, SingleTableMixin
from django_filters.views import FilterView

from clients.models import Client
from clients.forms import ClientForm
from clients.tables import ClientTable
from clients.filter import ClientFilter

from insurance_clients_tracker.views import LoginRequiredView

# List view for displaying a list of clients
# class defined views
# class ClientListView(LoginRequiredView, ListView):
#     model = Client
#     template_name = "client/client_list.html"
#     context_object_name = "clients"
class ClientListView(LoginRequiredView, SingleTableMixin, FilterView):
    model = Client
    template_name = "client/client_list_table.html"
    #context_object_name = "clients"
    table_class = ClientTable
    filterset_class = ClientFilter

# Detail view for displaying client details
class ClientDetailView(LoginRequiredView, DetailView):
    model = Client
    template_name = "client/client_detail.html"
    context_object_name = "client"


class ClientDetailView(LoginRequiredView, DetailView):
    model = Client
    template_name = "client/client_detail.html"
    context_object_name = "client"

    def get(self, request, *args, **kwargs):
        client = self.get_object()
        form = ClientForm(instance=client)
        return render(request, self.template_name, {'client': client, 'form': form})


# # Create view for adding a new client
# class ClientCreateView(CreateView):
#     model = Client
#     template_name = "client/client_form.html"
#     fields = "__all__"  # You can customize the fields to be displayed
#     success_url = reverse_lazy(
#         "client_list"
#     )  # Redirect to the client list view after successful creation


# # Update view for editing client details
# class ClientUpdateView(UpdateView):
#     model = Client
#     template_name = "client/client_form.html"
#     fields = "__all__"  # You can customize the fields to be displayed
#     context_object_name = "client"
#     success_url = reverse_lazy(
#         "client_list"
#     )  # Redirect to the client list view after successful update
    
class ClientCreateView(LoginRequiredView, CreateView):
    model = Client
    form_class = ClientForm
    template_name = "client/client_form.html"
    success_url = reverse_lazy("client_list")

class ClientUpdateView(LoginRequiredView, UpdateView):
    model = Client
    form_class = ClientForm
    template_name = "client/client_form.html"
    context_object_name = "client"
    success_url = reverse_lazy("client_list")


# Delete view for deleting a client
class ClientDeleteView(LoginRequiredView, DeleteView):
    model = Client
    template_name = "client/client_confirm_delete.html"
    context_object_name = "client"
    success_url = reverse_lazy(
        "client_list"
    )  # Redirect to the client list view after successful deletion
    
class BirthdayClientsView(LoginRequiredView, View):
    template_name = 'client/birthday_clients.html'

    def get(self, request, *args, **kwargs):
        # Get today's date
        today = timezone.now().date()

        # Calculate yesterday and tomorrow
        yesterday = today - timedelta(days=1)
        tomorrow = today + timedelta(days=1)

        # Query clients with birthdays yesterday, today, and tomorrow (ignoring the year)
        clients_yesterday = Client.objects.filter(
            birthday__month=yesterday.month,
            birthday__day=yesterday.day
        )

        clients_today = Client.objects.filter(
            birthday__month=today.month,
            birthday__day=today.day
        )

        clients_tomorrow = Client.objects.filter(
            birthday__month=tomorrow.month,
            birthday__day=tomorrow.day
        )

        context = {
            'clients_yesterday': clients_yesterday,
            'clients_today': clients_today,
            'clients_tomorrow': clients_tomorrow,
        }

        return render(request, self.template_name, context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <title>Clients Tracker</title>

    <!-- ***** BOOTSTRAP ***** -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous" />
    <!-- ***** CSS ***** -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
  </head>
  <body>
    {% comment %} KIRE: This is a base tempalte file. This template is used as a boilerplate, so that you don't need to write the redundant "HTML" code
    every time you create a new view (page). The navbar block "content" is where all content from another templates will be displayed. {% endcomment %}
    {% block navbar %}
      <header>
        {% comment %} KIRE: Feel free to add to the navbar all views you can think of (use the screenshot from the legacy app to acquire what apps we need) {% endcomment %}
        {% if user.is_authenticated %}
        <nav class="navbar navbar-expand-lg mx-auto container">
          <div class="collapse navbar-collapse d-flex justify-content-between">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'client_list' %}">Clients</a>
                {% comment %} <a class="nav-link" href="">Clients</a> {% endcomment %}
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'insurance_list' %}">Insurances</a>
                {% comment %} <a class="nav-link" href="">Insurances</a> {% endcomment %}
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'birthday_view' %}">Birthday View</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">View 3</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/logout">Logout</a>
              </li>
            </ul>
          </div>
        </nav>
        {% endif %}
      </header>
    {% endblock %}

    {% block content %}
      {# content #}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
  </body>
</html>

templates/clients.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container">
        <h1>Clients view</h1>
    </div>
</main>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container">
        <h1>Clients tracker home view</h1>
        <p>KIRE: The home view of the app. Basic info can be shown here, and quick "add" buttons for new clients, as well as overview of clients birthday etc...</p>
    </div>
</main>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="login-form" >
    <form method="POST" action="{% url 'login' %}">
      <p>{{ message }}</p>
      <p>{{error}}</p>
      {% csrf_token %}

      <!-- Email input -->
      <div class="form-outline mb-4">
        <label class="form-label" for="login-username">Username</label>
        <input type="text" id="login-username" class="form-control" name="username" />
      </div>

      <!-- Password input -->
      <div class="form-outline mb-4">
        <label class="form-label" for="login-password">Password</label>
        <input type="password" id="login-password" class="form-control" name="password" />
      </div>

      <!-- Submit button -->
      <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
    </form>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
{% endblock %}

templates/sign-in.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- Section -->
<section class="vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
  <div class="container">
    <p class="text-center">
      <a href="{% url 'dashboard' %}" class="d-flex align-items-center justify-content-center">
        <svg class="icon icon-xs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd"
            d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z"
            clip-rule="evenodd"></path>
        </svg>
        Back to homepage
      </a>
    </p>
    <div class="row justify-content-center form-bg-image"
      data-background-lg="{% static 'assets/img/illustrations/signin.svg' %}">
      <div class="col-12 d-flex align-items-center justify-content-center">
        <div class="bg-white shadow border-0 rounded border-light p-4 p-lg-5 w-100 fmxw-500">
          <div class="text-center text-md-center mb-4 mt-md-0">
            <h1 class="mb-0 h3">Sign in to our platform</h1>
          </div>
          <form method="post" class="mt-4">
            {% csrf_token %}

            {% if form.non_field_errors %}
              {% for error in form.non_field_errors %}
                <div class="text-danger mb-3">{{ error }}</div>
              {% endfor %}
            {% endif %}

            <!-- Form -->
            <div class="form-group mb-4">
              <label for="email">{{ form.username.label }}</label>
              <div class="input-group">
                <span class="input-group-text" id="basic-addon1">
                  <svg class="icon icon-xs text-gray-600" fill="currentColor" viewBox="0 0 20 20"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                      d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-6-3a2 2 0 11-4 0 2 2 0 014 0zm-2 4a5 5 0 00-4.546 2.916A5.986 5.986 0 0010 16a5.986 5.986 0 004.546-2.084A5 5 0 0010 11z"
                      clip-rule="evenodd"></path>
                  </svg>
                </span>
                {{ form.username }}
              </div>
            </div>
            <!-- End of Form -->
            <div class="form-group">
              <!-- Form -->
              <div class="form-group mb-4">
                <label for="password">{{ form.password.label }}</label>
                <div class="input-group">
                  <span class="input-group-text" id="basic-addon2">
                    <svg class="icon icon-xs text-gray-600" fill="currentColor" viewBox="0 0 20 20"
                      xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd"
                        d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z"
                        clip-rule="evenodd"></path>
                    </svg>
                  </span>
                  {{ form.password }}
                </div>
              </div>
              <!-- End of Form -->
              <div class="d-flex justify-content-between align-items-top mb-4">
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="remember">
                  <label class="form-check-label mb-0" for="remember">
                    Remember me
                  </label>
                </div>
                <div><a href="{% url 'password_reset' %}" class="small text-right">Lost password?</a></div>
              </div>
            </div>
            <div class="d-grid">
              <button type="submit" class="btn btn-gray-800">Sign in</button>
            </div>
          </form>
          <!--
          <div class="mt-3 mb-4 text-center">
            <span class="fw-normal">or login with</span>
          </div>
          <div class="d-flex justify-content-center my-4">
            <a href="#" class="btn btn-icon-only btn-pill btn-outline-gray-500 me-2" aria-label="facebook button"
              title="facebook button">
              <svg class="icon icon-xxs" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="facebook-f"
                role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512">
                <path fill="currentColor"
                  d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z">
                </path>
              </svg>
            </a>
            <a href="#" class="btn btn-icon-only btn-pill btn-outline-gray-500 me-2" aria-label="twitter button"
              title="twitter button">
              <svg class="icon icon-xxs" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="twitter"
                role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                <path fill="currentColor"
                  d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z">
                </path>
              </svg>
            </a>
            <a href="#" class="btn btn-icon-only btn-pill btn-outline-gray-500" aria-label="github button"
              title="github button">
              <svg class="icon icon-xxs" aria-hidden="true" focusable="false" data-prefix="fab" data-icon="github"
                role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512">
                <path fill="currentColor"
                  d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z">
                </path>
              </svg>
            </a>
          </div>-->
          <div class="d-flex justify-content-center align-items-center mt-4">
            <span class="fw-normal">
              Not registered?
              <a href="{% url 'register' %}" class="fw-bold">Create account</a>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}